UPDATE_PROCESS_IDENTIFICATION_ID=
UPDATE
  FILE_CREATE_REQUEST
SET
  PROCESS_IDENTIFICATION_ID = ?
WHERE
  PROCESS_IDENTIFICATION_ID IS NULL

CLEAR_PROCESS_IDENTIFICATION_ID=
UPDATE
  FILE_CREATE_REQUEST
SET
  PROCESS_IDENTIFICATION_ID = NULL
WHERE
  PROCESS_IDENTIFICATION_ID = ?

FIND_BY_PROCESS_IDENTIFICATION_ID=
SELECT
  *
FROM
  FILE_CREATE_REQUEST
WHERE
  PROCESS_IDENTIFICATION_ID = ?

